fehler bei TUC-C:
Tldr: Image nicht gefunden obwohl vorhanden
-> MÃ¶gliche Fehler gem. Recherche:
- GPU usage reaching its limit (https://github.com/ultralytics/ultralytics/issues/6379)
- Korrupte/unlesbare Bilder
- zu viele workers




Traceback (most recent call last):
  File "G:\HSLU\.Workspace\P3_coco-mix\train.py", line 25, in <module>
    main()
  File "G:\HSLU\.Workspace\P3_coco-mix\train.py", line 22, in main
    results = model.train(data = data, epochs = int(args.epochs), imgsz = 640, freeze = range(freeze_N), batch = int(args.batch), workers = int(args.workers), device = int(args.gpu),lr0 = args.learnrate, project = parent, name = saveto)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\engine\model.py", line 802, in train
    self.trainer.train()
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\engine\trainer.py", line 362, in _do_train
    for i, batch in pbar:
                    ^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\data\build.py", line 48, in __iter__
    yield next(self.iterator)
          ^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\torch\utils\data\dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\torch\utils\data\dataloader.py", line 1491, in _process_data
    data.reraise()
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\torch\_utils.py", line 715, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\torch\utils\data\_utils\worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\data\base.py", line 288, in __getitem__
    return self.transforms(self.get_image_and_label(index))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\data\base.py", line 294, in get_image_and_label
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
                                                               ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Projects\denisAmeti\Env\envs\BATdenis\Lib\site-packages\ultralytics\data\base.py", line 165, in load_image
    raise FileNotFoundError(f"Image Not Found {f}")
FileNotFoundError: Image Not Found G:\HSLU\.Workspace\data\TUC-C\images\train\001_img.png

(BATdenis) G:\HSLU\.Workspace>P3_coco-mix\batch_P3.bat